### ISSUE TITLE
BSRKey and LevelID values in the MapData endpoint are (usually) null [1.39.1]

### ISSUE THREAD

**Issue by TheBlackParrot** [DJDavid98/BSDataPuller#10]
Noticed today while working on a thing that the BSRKey and LevelID values in the MapData endpoint usually return as null (they seem to work about, 10% of the time?), when I know previously these both worked fine in older game versions.

Not a _huge_ inconvenience, but I figured I would bring it up.
Nothing odd in logs either, maybe something's just prematurely firing? idk

SongDetailsCache is installed fwiw

**Comment by WentTheFox** [comment]
I'll need to have a look later, if you have any example map IDs where this happens please do share them. It'd also be good to know if this happens regularly for specific maps or at random and sometimes the data is available for the same map and sometimes not.

**Comment by TheBlackParrot** [comment]
Any map, also pretty sure something just is firing early. If I pause the map (while my script is connected to the MapData endpoint) and restart the script after a few seconds, the key appears in the data. If I then exit the map and open another map (while the script is running), BSRKey becomes null again. If I restart the script again to trigger a reconnection, it appears.

**Comment by TheBlackParrot** [comment]
Actually forgot MapData triggers multiple times woops
The first few events that fire leave BSRKey as null, but later events have it populated.
[debug.txt](https://github.com/user-attachments/files/17918313/debug.txt)
(Spat out MapData data as it was coming in)

**Comment by WentTheFox** [comment]
This is actually "by design", the mod sends out the object if any property of it changes, it does not wait for a specific time to send the update. I would suggest listening to the events as they come in and getting the info out of it when it gets populated, that's what I've been doing in my overlay as well.

**Comment by TheBlackParrot** [comment]
Yep, just misunderstood how to handle it, no problem
