### ISSUE TITLE
Possible to have a data type for leaderboard

### ISSUE THREAD

**Issue by an0Nym0us63** [DJDavid98/BSDataPuller#6]
Hello great mod and happy that you decided to continue the work.

Do you think it IS possible to trigger an event on party mode at the same Time the localeaderboard.dat IS updated.

Containing the title hash and so on and also thé scoredatas and accuracy and missed among with the name types

For now i try to link the datas between thé localleaderboard.dat and the websocket to create a localleaderboard AT home with stats and so on 

But receiving those on the websocket with the complementary data would be a great and easy addition.

Regards

**Comment by WentTheFox** [comment]
Hi, please check the newly-released [v2.1.12](https://github.com/DJDavid98/BSDataPuller/releases/tag/v2.1.12) update and the new PartyData endpoint, hopefully this helps.

**Comment by an0Nym0us63** [comment]
Oh thank you for your feedback.

Do you think it is possible to add scoredata when a score is submitted at the end
That will avoid to go check livedata to get missed, accuracy, total notes and some statistics available on livedata.

I think just appending the last livedata should be ok and maybe the full songdata as i think total notes is there

**Comment by WentTheFox** [comment]
I don't want to duplicate data, and there is no guarantee that the leaderboard data matches the last live data, especially since the leaderboard is re-sent when another song is selected. I suggest you subscribe to both endpoints and manually correlate the data.

**Comment by an0Nym0us63** [comment]
> I don't want to duplicate data, and there is no guarantee that the leaderboard data matches the last live data, especially since the leaderboard is re-sent when another song is selected. I suggest you subscribe to both endpoints and manually correlate the data.

Ok i will do it like that.

Thanks for your Quick release
